on:
  push:
    branches:
      - qa1

env:
  svcArray: ""

jobs:
  matrixJob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [""]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
           fetch-depth: 10        

      - name: Get Modified Files
        id: getModifiedFiles
        run: |

          files=$(git diff-tree --no-commit-id --name-only -r HEAD)


          echo "::set-output name=modifiedFiles::$files"

      - name: Use Modified Files
        run: |

          modifiedFiles="${{ steps.getModifiedFiles.outputs.modifiedFiles }}"

          IFS=$'\n' read -rd '' -a modifiedFilesArray <<< "$modifiedFiles"

          echo "Matrix File: ${{ matrix.file }}"
          echo "Modified Files: ${modifiedFilesArray[${{ matrix.file }}]}"
             

      