on:
  push:
    branches:
      - qa1

env:
  BRANCH_NAME: master

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      - name: check logs
        id: checklogs
        run: |
            git clone https://github.com/Nitik-git/actionsGeneric.git
            git log

      # - name: test git
      #   run: |
      #      files=$(git log -1 --name-only --pretty=format:)
      #      echo "$files"
            
      - name: Fetch Last Commit
        id: fetchLastCommit
        run: |
        
          commit=$(git log -1 --pretty=format:%h)

          
          files=$(git show --name-only --pretty=format:%h $commit)

          echo "$files"

      
    # echo "::set-output name=commitID::$commit"
    # echo "::set-output name=changedFiles::$files"

      # - name: Print Last Commit Details
      #   run: |

      #     commitID="${{ steps.fetchLastCommit.outputs.commitID }}"
      #     changedFiles="${{ steps.fetchLastCommit.outputs.changedFiles }}"
      #     echo "Changed Files:"
      #     echo "$changedFiles"