name: makegeneric

on:
  push:
    branches:
      - qa1
  workflow_call:
    outputs:
      matrix:
        value: ${{ jobs.create_array.outputs.matrix }}

jobs:
  create_array:
    runs-on: ubuntu-latest
    outputs:
      matrix:  ${{steps.createarray.outputs.matrix}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           fetch-depth: 10  
                       
      - name: create files array
        id: createarray
        run: |-
              TESTING=`git diff-tree --no-commit-id --name-only -r HEAD | awk -F/ '{ print $1}' | uniq | sed -n -e '/api/p' -e '/assessment/p'` 
              svcArray=(`echo ${TESTING}`)
              sudo apt-get install jo
              echo "matrix=$(jo -a "${svcArray[@]}" )" >> $GITHUB_OUTPUT

    
  check_file:
    needs: create_array
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: {[api,assessment] }                                   
    steps:
      - name: update path
        id: updatepath
        run: |-
          echo "${{ matrix.target }}"
          echo ${{ needs.create_array.outputs.matrix }}
               
             

      