on:
  push:
    branches:
      - qa1

env:
  BRANCH_NAME: master

jobs:
  check_file:
    runs-on: ubuntu-latest
    # env:
    #   TESTING=`git diff-tree --no-commit-id --name-only -r HEAD | awk -F/ '{ print $1}' | uniq | sed -n -e '/api/p' -e '/assessment/p'`
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: fetch svcd
        run: |-
              echo hii

      - name: fetch svc
        run: |-
              echo "::set-output name=TESTING::$(git diff-tree --no-commit-id --name-only -r HEAD | awk -F/ '{ print $1}' | uniq | sed -n -e '/api/p' -e '/assessment/p')
      
      - name: Update-file
        run: |-
            
            echo ${{ steps.setOutput.outputs.TESTING }}
