name: makegeneric

on:
  push:
    branches:
      - qa1

jobs:
  create_array:
    runs-on: ubuntu-latest
    outputs:
      matrix:  ${{steps.createarray.outputs.matrix}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           fetch-depth: 10  
                       
      - name: create files array
        id: createarray
        run: |-
              TESTING=`git diff-tree --no-commit-id --name-only -r HEAD | awk -F/ '{ print $1}' | uniq | sed -n -e '/api/p' -e '/assessment/p'` 
              svcArray=(`echo ${TESTING}`)
              sudo apt-get install jo
              echo "::set-output name=matrix::$(jo -a "${svcArray[@]}" )"
    
  check_file:
    needs: create_array
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     subdir:    ${{fromJson(needs.set.outputs.matrix)}}                                          
    steps:
      - name: update path
        id: updatepath
        run: |-
             echo  ${{fromJson(needs.createarray.outputs.matrix)}}     
             

      