on:
  push:
    branches:
      - master

env:
  BRANCH_NAME: master

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - run: | 
            git diff-tree --no-commit-id --name-only -r HEAD | cat > file1.txt
            

  print_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
