on:
  push:
    branches:
      - qa1

env:
  BRANCH_NAME: master

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test git
        run: |
            files=$(git diff-tree --no-commit-id --name-only -r HEAD)
            echo "::set-output name=changedFiles::$files"
            

      - name: fetch svc
        run: |-
             changedFiles="${{ steps.fetchFiles.outputs.changedFiles }}"
             echo "$changedFiles"
      

