on:
  push:
    branches:
      - qa1

env:
  BRANCH_NAME: master

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           fetch-depth: 10

      - name: check logs
        id: checklogs
        run: |-

           
              TESTING=`git diff-tree --no-commit-id --name-only -r HEAD | awk -F/ '{ print $1}' | uniq | sed -n -e '/api/p' -e '/assessment/p'` 
              svcArray=(`echo ${TESTING}`)
              echo "svcArray" >> $GITHUB_ENV

      - name: update path
        id: updatepath
        run: |-
             echo $svcArray[1]
             echo $svcArray[2]
            

