on:
  push:
    branches:
      - qa1

env:
  BRANCH_NAME: master

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: fetch svcd
        run: |-
              echo hii

      - name: fetch svc
        run: |-
              git branch
              git diff-tree --no-commit-id --name-only -r HEAD
              echo "TESTING=$(git diff-tree --no-commit-id --name-only -r HEAD | awk -F/ '{ print $1}' | uniq | sed -n -e '/api/p' -e '/assessment/p)" >> $GITHUB_ENV 
              echo $TESTING
      
      - name: Update-file
        run: |-
            echo "${{ env.TESTING }}"
