name: availability-workflow

on:
  pull_request:
    types: [opened]
    branches-ignore:
      - 'qa1'
      - 'qa2'

# permissions:
#   actions: write

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: display branch
        run: git branch   

      - name: Check PR for Base Ref
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          BASE_REF: "qa1,qa2" # Replace with the base reference you want to check
        run: |
          # Install jq for JSON parsing
          sudo apt-get update && sudo apt-get -y install jq

          # Split the BASE_REFS environment variable into an array
          IFS=',' read -ra BASE_REF_ARRAY <<< "$BASE_REFS"

          # Initialize an empty array to store branch names
          BRANCHES_WITH_PR=()

          # Iterate through the base references and check for open pull requests
          for BASE_REF in "${BASE_REF_ARRAY[@]}"; do
            prs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/pulls?base=$BASE_REF")

            # Check if there are any open pull requests
            if [ "$(echo "$prs" | jq length)" -gt 0 ]; then
              BRANCHES_WITH_PR+=("$BASE_REF")
            fi
          done

          # Print the branch names with open pull requests
          if [ "${#BRANCHES_WITH_PR[@]}" -gt 0 ]; then
            echo "Branches with open pull requests: ${BRANCHES_WITH_PR[@]}"
          else
            echo "No open pull requests found for any branches."
          fi
