name: availability-workflow

on:
  push:
    branches:
      - 'test/PRtrigger'

# permissions:
#   actions: write

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: display branch
        run: git branch   

      - name: Check PR for Base Ref
        run:          
              qa1_str=$(gh pr list --base qa1)
              # qa1_ext=$(echo $qa1_str | sed 's/.*\(#\).*/\1/')
              if [[ "$qa1_str" =~ ^[0-9]+ ]]; then
                qa1_mess="qa1 is occupied"
              fi
              qa2_str  =$(gh pr list --base qa2)
              if [[ "$qa2_str" =~ ^[0-9]+ ]]; then
                qa2_mess="qa2 is occupied"
              fi
              qa3_str  =$(gh pr list --base qa3)
              if [[ "$qa3_str" =~ ^[0-9]+ ]]; then
                qa3_mess="qa3 is occupied"
              fi
              message = $qa1_mess"\n"$qa2_mess"\n"$qa3_mess
              echo $message

