name: availability-workflow

on:
  pull_request:
    types: [opened]
    branches-ignore:
      - 'qa1'
      - 'qa2'

# permissions:
#   actions: write

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: display branch
        run: git branch   

      - name: Check availability of QA
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |-          
              qa1_str=$(gh pr list --base qa1)
              if [[ "$qa1_str" =~ ^[0-9]+ ]]; then
                qa1_mess="qa1 is occupied"
              fi

              qa2_str=$(gh pr list --base qa2)
              if [[ "$qa2_str" =~ ^[0-9]+ ]]; then
                qa2_mess="qa2 is occupied"
              fi

              qa3_str=$(gh pr list --base qa3)
              if [[ "$qa3_str" =~ ^[0-9]+ ]]; then
                qa3_mess="qa3 is occupied"
              fi

              
              git fetch origin qa1
              git checkout qa1
              log=`glo --skip=1 -n 1`
              if [[ $log != *origin/main, origin/HEAD, main* ]]; then
                qa1_mess="qa1 is occupied"

              git fetch origin qa2
              git checkout qa2
              log=`glo --skip=1 -n 1`
              if [[ $log != *origin/main, origin/HEAD, main* ]]; then
                qa2_mess="qa2 is occupied"

              
              message=$(echo -e "$qa1_mess\n$qa2_mess\n$qa3_mess" | sed '/^$/d')
              echo "msg=$message" >> "$GITHUB_ENV"

              my_array=()

              if [ -z "$qa1_mess" ]; then
                my_array+=("qa1")
              fi

              if [ -z "$qa2_mess" ]; then
                my_array+=("qa2")
              fi

              if [ -z "$qa3_mess" ]; then
                my_array+=("qa3")
              fi
                
              echo "MY_ARRAY=${my_array[@]}" >> $GITHUB_ENV



      - name: 'Create PR'
        if: env.MY_ARR != 'null'
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}      
        run: |-
          first_value=$(echo "$MY_VAR" | sed 's/ .*//')
          echo "test=$first_value" >> "$GITHUB_ENV"
          gh pr list
          git branch
          gh pr create -B "proof-v10-${{ env.test }}" -t "this is test" -b testiiing

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.NA_WEBHOOK_URL }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: '${{ env.test }} is available'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp

