name: gh-testing

on:
  push:
    branches:
      - 'test-ff-merge'

jobs:
  gh:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-ff-merge
      - name: Check availability of QA
        run: |-          
          touch fffile.txt
      - name: merge
        run: |-
          git fetch origin master
          git checkout master
          git merge test-ff-merge
          ls
