name: gh-testing

on:
  push:
    branches:
      - 'test/PRtrigger'

jobs:
  gh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check availability of QA
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |-          
              gh pr list
