name: notification-workflow

on:
  # workflow_dispatch:
  # push:
  #   branches:
  #     - test/checkout
  push:
    branches:
      - test/notification-slack

# permissions:
#   actions: write

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: display branch
        run: git branch        

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.NA_WEBHOOK_URL }}
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: Proof-qa-alert
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAM1BMVEVHcEwODg4ODg4ODg4AAADd29dgYF6+vLj///uCgX8+Pj2Uk5CmpKHv7ej7+fTQz8oiIiFQghxUAAAAA3RSTlMApfydDTJFAAAArElEQVR4AbWTCwrEIAwFrT5t/Pf+p92VSFngWWGh4c9M2gGMMYd1y7HHl7vHOYx9Fqxxm/lXADaCD1gLAE6JVFCashcmKA2lirTGhEHPNmgTIQJiH3BQnwsTmu72CMTGhKr0GolckIykiY0LdVKRei5+MRMveCrciX3V4GfisiH9RCTaMGkJABwRNDEpZYL0fCkFFeTeRUhE8OXeo19wwPbRviRsT297vNvz/wDWFhHLlYoQHgAAAABJRU5ErkJggg==
