name: My Github Action

on:
  push:
    branches:
      - qa1
      - qa2
      - qa3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          echo "running1"

      - name: Setup Node.js
        run: |
          echo "running2"

      - name: Deploy to main
        if: github.ref == 'refs/heads/qa2'
        run: |
          echo "hello qa2"
