name: checkout-workflow

on:
  # workflow_dispatch:
  #   inputs:
  #     serviceCount: 
  #       description: "Enter number of nodes required in services nodepool"
  #       default: 2
  #     githubrunnerCount:
  #       description: "Enter number of nodes required in github-runner nodepool"
  #       default: 0
  # push:
  #   branches:
  #     - test/checkout
  push:
    tags:
      - prod-*

jobs:
  services_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for Push
        uses: actions/checkout@v2

      - name: which branch on tag
        run: git branch

      - name: Display branch name
        id: branchname
        run: |-
          git checkout main
          git branch
