name: checkout-workflow

on:
  # workflow_dispatch:
  #   inputs:
  #     serviceCount: 
  #       description: "Enter number of nodes required in services nodepool"
  #       default: 2
  #     githubrunnerCount:
  #       description: "Enter number of nodes required in github-runner nodepool"
  #       default: 0
  # push:
  #   branches:
  #     - test/checkout
  push:
    tags:
      - prod-*

jobs:
  services-list1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for Push
        uses: actions/checkout@v2

      - name: which branch on tag
        run: echo $GITHUB_REF

      - name: extract tag name
        run: echo $GITHUB_REF | awk -F'/' '{split($3, arr, "-"); print arr[2]}'

      - name: Display branch name
        id: branchname
        run: |-
          echo ${{ github.event}}
          echo ${{ github.event.ref }}

  services-list2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for Push
        uses: actions/checkout@v2
      - name: extract tag name
        run: echo hello
  services-list:
    runs-on: ubuntu-latest
    needs: [services-list1,services-list2]
    steps:
      - name: Checkout for Push
        uses: actions/checkout@v2
      - name: extract tag name
        run: echo hii
