name: checkout-workflow

on:
  workflow_dispatch:
    inputs:
      serviceCount: 
        description: "Enter number of node"
        default: 2
  # push:
  #   branches:
  #     - test/checkout

jobs:
  services_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for Push
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        uses: actions/checkout@v2
        with:
          ref: qa1

      - name: Display branch name
        id: branchname
        run: |-
          git branch
          echo "Total node ${{ github.event.inputs.serviceCount }}"
